### ISSUE TITLE
使用反馈，存在已有文件加载和文件保存问题

### ISSUE THREAD

**Issue by Genius2333** [henryau53/xmind-crack-patch#1]
经使用无法打开本地已有的xmind文件，且使用该补丁后新创建的文件无法保存
![QQ截图20230909103825](https://github.com/henryau53/xmind-crack-patch/assets/139752467/3b24d408-c987-4383-80da-dd0b31da02b8)
![QQ截图20230909103725](https://github.com/henryau53/xmind-crack-patch/assets/139752467/e85398a1-33d3-421b-9ce7-990a2f69d220)

**Comment by henryau53** [comment]
我这边在 MacOS、Linux、Windows 测试均正常，破解仅解开了 Pro 功能，并未碰触功能性内容，能否提供更详细的描述？包括系统版本，Xmind 版本，请保证你使用的 Xmind 版本为 Xmind 23.08.02122，不过我并未测试使用 Xmind 23.08.02122 的版本打开老版本保存的 xmind 文件。

**Comment by henryau53** [comment]
在 Windows 系统确实会出现无法保存和无法打开老版本文件的问题，因为我的主力电脑是 Linux，我会抽时间看下这个问题

**Comment by henryau53** [comment]
抽空看了下代码，由于 Windows 使用了字节码的形式载入 main.js，如果需要完美“体验”可能需要其他方式处理，由于最近比较忙，暂无精力处理 Windows 版本的“体验”，所以暂时不推荐 Windows 使用此补丁。

**Comment by Genius2333** [comment]
最近没怎么关注这问题了，从别处找到了能运行的数据包
有机会的话我试试大佬你的
感谢


| |
18844095046
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Henry ***@***.***> |
| 发送日期 | 2023年9月16日 15:06 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [henryau53/xmind-crack-patch] 使用反馈，存在已有文件加载和文件保存问题 (Issue #1) |

Closed #1 as completed.
