### ISSUE TITLE
存在无法保存的现象

### ISSUE THREAD

**Issue by pengbowen218** [henryau53/xmind-crack-patch#2]
![image](https://github.com/henryau53/xmind-crack-patch/assets/13193671/d30c4a4f-be9d-42de-8980-5c5642f6139d)

**Comment by henryau53** [comment]
如图所示，你所保存的路径我不知道为什么会变成 C:\D:\中心主题.xmind 这种形式，出现了两个盘符路径，报错原因是保存的路径不存在，因为保存的地址是有问题的，你那边是如何操作的？在保存时重新选择其他路径也会出现这种错误路径吗？

**Comment by henryau53** [comment]
在 Windows 系统确实会出现无法保存和无法打开老版本文件的问题，因为我的主力电脑是 Linux，我会抽时间看下这个问题

**Comment by henryau53** [comment]
抽空看了下代码，由于 Windows 使用了字节码的形式载入 main.js，如果需要完美“体验”可能需要其他方式处理，由于最近比较忙，暂无精力处理 Windows 版本的“体验”，所以暂时不推荐 Windows 使用此补丁。
