### ISSUE TITLE
想请教一下在您的版本上破解完全吗

### ISSUE THREAD

**Issue by erichza** [henryau53/xmind-crack-patch#3]
我是最新版的windows xmind，使用了您的[app.asar.windows]破解，pro登录页面消失了但是不能使用pro功能，请问这是正常情况吗

**Comment by henryau53** [comment]
@erichza 是的，你描述的是正常情况，在 README 中有说明，现在仅限 MacOS 与 Linux，因为 Windows 中的主程序使用了字节码加密形式，所以 Windows 的破解还不完全，存在问题的，由于最近比较忙只进行了一半，所以很抱歉，没有帮助到你。
可以在网上找找老版本的破解补丁，有些老版本针对 Windows 还是可以用的，或者还有一种使用序列号注册的形式，只不过每次开启前和关闭后都需要更改系统时间。
