### ISSUE TITLE
Cannot save files

### ISSUE THREAD

**Issue by Ziggizag** [henryau53/xmind-crack-patch#8]
With this app.asar patch XMind files cannot be saved, because of wrong path like this (pls. notice C:\C:\)

![Xmind_Error](https://github.com/henryau53/xmind-crack-patch/assets/2280036/c95e47cf-aec2-4aa0-9cd2-50c13b4ea20b)

**Comment by henryau53** [comment]
If you are using a Windows system, I'm sorry, bro. It's already stated in the README that Windows system is not currently supported. it only works on Linux and MacOS for now.

**Comment by Ziggizag** [comment]
Ouups - indeed :-(

Well - I do not want to insist, but this looks like some pretty little flaw, very easy to correct for someone like you, who already know the structure of the code. All the other functions work as expected. I simply encourage you to reconsider your decision and correct just this one issue. It would be appreciated, I am sure.

Regards,
Ziggi.

**Comment by henryau53** [comment]
I did try to handle the Windows version, but after 2 days of attempts, it still didn't work. The patch for Linux/macOS seem to have no issues on Windows, but in reality, they are completely incompatible (and may even cause some other problems), because the framework used by XMind "encrypts" the core files of the Windows version to prevent cracking.

**Comment by Ziggizag** [comment]
OK, I understand - you cannot correct it in a simple manner - then it's not worth more work. Thank you for your kind try!

Anyway - is it possible to post here linux-compiled version of app.asar file? I would love give it a chance. I am not compilation expert myself.

**Comment by Ziggizag** [comment]
@henryau53  No problemo - I magaged to compile it myslef !

**Comment by Ziggizag** [comment]
@henryau53 And nope - unfortunately, non-windows patch suffers from the same issue on Windows:

![image](https://github.com/henryau53/xmind-crack-patch/assets/2280036/3c80752b-ce0c-4bc7-a464-fede48fd3989)

**Comment by Ziggizag** [comment]
Ha !!!

I found the solution !!!

1. I used 7-Zip to unpack the installation file "Xmind-for-Windows-x64bit-23.08.02122-202308280055.exe" downloaded from this repo.
2. Then I unpacked "app-64.7z" file within $PLUGINSDIR.
3. There is "app.asar.unpacked" directory inside and inside there is "node_modules" subdirectory.
4. I copy-pasted this entire directory into "app.asar.windows" directory of your patch. There were differences!
5. I compiled, and - BINGO! no more this nasty error!

You may download this (zipped) app.asar here:

https://www.dropbox.com/scl/fi/eviivbkafknbxfwnqb2y5/app.asar.zip?rlkey=1bcmig7jv40oquw2rsichkzno&st=r9j3y245

**Comment by henryau53** [comment]
> @henryau53 And nope - unfortunately, non-windows patch suffers from the same issue on Windows:
> 
> ![image](https://private-user-images.githubusercontent.com/2280036/324608597-3c80752b-ce0c-4bc7-a464-fede48fd3989.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODQzMzYsIm5iZiI6MTcxMzg4NDAzNiwicGF0aCI6Ii8yMjgwMDM2LzMyNDYwODU5Ny0zYzgwNzUyYi1jZTBjLTRiYzctYTQ2NC1mZWRlNDhmZDM5ODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMTQ1MzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTUwZTExNGU5Mjc3MzgwNWI3ODUwNjViM2MzZjQ3OWFlZmY1NmM2YTAxYzliNTQ5OTU2OTM0NjVlNWU5ZDJlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.N94YAzTi5e6QAq2g_rcla9ar5wz3K-mfX7I1fbqrzzU)

Wow, I've been quite busy these past couple of days and haven't been online. You've actually replied so much and so many things have happened.
Just as I mentioned earlier, patch is not compatible between Windows and non-Windows versions.

**Comment by henryau53** [comment]
> OK, I understand - you cannot correct it in a simple manner - then it's not worth more work. Thank you for your kind try!
> 
> Anyway - is it possible to post here linux-compiled version of app.asar file? I would love give it a chance. I am not compilation expert myself.

The patch file app.asar can be downloaded from Releases, which is compiled for Linux/MacOS systems. However, it cannot be used on Windows systems.

**Comment by henryau53** [comment]
> Ha !!!
> 
> I found the solution !!!
> 
> 1. I used 7-Zip to unpack the installation file "Xmind-for-Windows-x64bit-23.08.02122-202308280055.exe" downloaded from this repo.
> 2. Then I unpacked "app-64.7z" file within $PLUGINSDIR.
> 3. There is "app.asar.unpacked" directory inside and inside there is "node_modules" subdirectory.
> 4. I copy-pasted this entire directory into "app.asar.windows" directory of your patch. There were differences!
> 5. I compiled, and - BINGO! no more this nasty error!
> 
> You may download this (zipped) app.asar here:
> 
> https://www.dropbox.com/scl/fi/eviivbkafknbxfwnqb2y5/app.asar.zip?rlkey=1bcmig7jv40oquw2rsichkzno&st=r9j3y245

You're great, that's really good news 👍. I'll make time to try out the solution you mentioned later.

**Comment by henryau53** [comment]
> > Ha !!!
> > I found the solution !!!
> > 
> > 1. I used 7-Zip to unpack the installation file "Xmind-for-Windows-x64bit-23.08.02122-202308280055.exe" downloaded from this repo.
> > 2. Then I unpacked "app-64.7z" file within $PLUGINSDIR.
> > 3. There is "app.asar.unpacked" directory inside and inside there is "node_modules" subdirectory.
> > 4. I copy-pasted this entire directory into "app.asar.windows" directory of your patch. There were differences!
> > 5. I compiled, and - BINGO! no more this nasty error!
> > 
> > You may download this (zipped) app.asar here:
> > https://www.dropbox.com/scl/fi/eviivbkafknbxfwnqb2y5/app.asar.zip?rlkey=1bcmig7jv40oquw2rsichkzno&st=r9j3y245
> 
> You're great, that's really good news 👍. I'll make time to try out the solution you mentioned later.

Hey, @Ziggizag , it's really been a long time. I took a look at the app.asar file you shared on Dropbox in the early hours and carefully reviewed the steps you mentioned earlier. I did a comparison:

The node_modules extracted from the .exe file.
The node_modules within app.asar.windows.
The node_modules found in the resources directory after installation.

After comparing all three, I found that there were no differences. As for the situation where replacing the file worked for you, I believe that during the first save error, you were using the app.asar.non-windows version of the patch, which is specifically for Linux and MacOS. Later, as you described, you used app.asar.windows, which is cracked for the Windows system, so it naturally didn't show the error anymore. However, this version hasn't been cracked successfully, as none of the pro features were unlocked. It's exactly the same as the official version installed.
